import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar";

const inter = Playfair_Display({ subsets: ["latin"], style: ["normal"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} container mx-auto `}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
